name: flutter_l10n_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  intl: ^0.15.8
  flutter_html: ^0.10.4
  flutter_markdown: ^0.2.0
  fps:
    git:
      url: https://github.com/amake/fps.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.5

flutter:
  uses-material-design: true
  fonts:
    - family: DM_Serif_Display
      fonts:
        - asset: assets/fonts/DM_Serif_Display/DMSerifDisplay-Regular.ttf
        - asset: assets/fonts/DM_Serif_Display/DMSerifDisplay-RegularItalic.ttf
          style: italic
